config/routes.rb
require 'resque/server'
FocusMail::Application.routes.draw do
  get "campaigns/test_job"
  get "user/edit"
  post "user/update_password"

  devise_for :users

  root :to => 'home#index'
  match 'open/getstate' => 'open#getstate'
  match 'open/sendmail' => 'open#sendmail'
  match 'track.gif' => 'respond#track'
  match 'click' => 'respond#click'
  match 'testcode' => 'testcode#index'
  post 'testcode/save'
  post 'campaigns/mailtest'
  post 'useradmins/saveupdate'
  match 'send_email' => 'home#send_email', via: 'post'
  match 'generate_email' => 'home#generate_email', via: 'get'
  match 'preview/:campaign_id' => "home#preview", :as => :preview
  get 'report/export'

  resources :links
  resources :campaigns
  resources :campaign_members
  resources :categories do
    get 'update_member_count', :on => :member
    get 'member_search', :on => :member
  end
  resources :templates do
    resources :entries
    get "download", :on => :collection
  end
  resources :lists do
    resources :members
  end
  resources :useradmins

 
  match 'templates/saveimgurl', via: 'post'
  match 'campaigns/template_entries/:c_id/:t_id' => 'campaigns#template_entries'
  match 'campaigns/:id/deliver/', controller: 'campaigns', action: 'deliver', as: 'deliver_campaign'
  match 'campaigns/:id/copies/', controller: 'campaigns', action: 'copies', as: 'copies_campaign'
  #match 'campaigns/:id/mailtest/', controller: 'campaigns', action: 'mailtest', as: 'mailtest_campaign'

  match 'campaigns/:campaign_id/record' => 'campaigns#record', :as => :campaigns_record
  match 'members/export/:list_id' => 'members#export', :as => :members_export
  get 'members/import_template'
  
  match 'members/imexport/:list_id' => 'members#imexport', :as => :members_imexport
  match 'members/import' => 'members#import', :via => :post
  match 'templates/grade/:template_id' => 'templates#grade', :as => :templates_grade
  match 'templates/preview/:template_id' => 'templates#preview', :as => :templates_preview
  
  match ':controller(/:action(/:id(.:format)))'
  
  mount Resque::Server.new, :at => '/resque'
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :org_id, :is_used
  #has_many :members
  has_and_belongs_to_many :members

  def org_id
    return @orgid
  end
  
  def org_id= (val)
    @orgid = val
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # GET /lists
  # GET /lists.json
  def index
   # @lists = List.all
   # @list = List.new
    user_id = current_user.id
    #userids = [6,7,8,9,10,12,13]
    if user_action_org then
      @lists = List.where(:is_used => true)
    else
      controller = "List"
      orglist = FocusMail::ListUserorg::userorg_list(user_id, controller)
      @lists = List.find(orglist).where(:is_used => true)
    end
    @list = List.new
    user_action_log(0,params[:controller],"index")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    redirect_to list_members_path(params[:id])
    user_action_log(params[:id],params[:controller],"show")
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    #@list = List.new
    user_id = current_user.id
    @list = List.new
    @list.org_id = FocusMail::ListUserorg::userorg_id(user_id)
    user_action_log(0,params[:controller],"new")

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
    user_action_log(params[:id],params[:controller],"edit")

    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])
    #is_used表示该名单列表在使用中
    @list.is_used = true

    respond_to do |format|
      if @list.save
        user_action_log(@list.id,params[:controller],"create")
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js { render action: "new" }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        user_action_log(params[:id],params[:controller],"update")
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js { render action: "edit" }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.update_attribute(:is_used,false)
    puts "*"*100
    puts "lists_controlle"
    #没有物理删除名单列表，可以恢复
    #@list.destroy
    user_action_log(params[:id],params[:controller],"delete")

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.js
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for @list, :html => { :class => 'form-horizontal' }, remote: true do |f| %>

  <%= render :partial => "common/form_error", :locals => { model: @list } %>
  <%= f.hidden_field :org_id %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn' %>
    <a onclick="$('#<%= dom_id @list, action_name %>').parent().html('');return false;", class='btn'>取消</a>
  </div>
<% end %>

app/views/lists/_list.html.erb
<tr id="<%= dom_id list %>">
  <td><%= link_to list.name, list_path(list) %></td>
  <td><%= list.members.size %></td>
  <td><%= list.created_at.strftime("%F %T") %></td>
  <td>
    <%= link_to '导入名单', members_imexport_path(list.id), :class => 'btn btn-mini' %>
    <%= link_to '添加名单', new_list_member_path(list.id), :class => 'btn btn-mini' %>
    <%= link_to '名单成员', list_path(list), :class => 'btn btn-mini' %>
    <%= link_to '编辑名单', edit_list_path(list), :class => 'btn btn-mini', :remote => true %>
    <%= link_to '删除名单', list_path(list), :method => :delete,
      :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger', :remote => true %>
  </td>
</tr>

app/views/lists/create.js.erb
$("<%= j render @list %>").appendTo('#lists').hide().fadeIn();
$('#new_list')[0].reset();

app/views/lists/destroy.js.erb
$("#<%= dom_id @list %>").remove();

app/views/lists/edit.js.erb
$("#form").html("<%= j render :partial => 'form' %>");
$("#form > form").replaceWith("<%= j render "form" %>");

app/views/lists/index.html.erb
<%- model_class = List.new.class -%>
	<div class="main-content" style="width:100%">
		<div class="page-header">
		  <table style="width:100%">
		   <tr>
		    <td><h2>名单管理</h2></td>
 		  	<td style="float:right">
  		  	  <div style="float:right">
           <%= link_to '新建名单列表', new_list_path, :class => 'btn btn-primary', remote: true %>
         </div>
  		  	</td>
 		  	</tr>
		  	</table>


        </div>
    <div  style="padding: 20px 20px 20px 20px">
        <div id="form"></div>
        <div id="sel_mes" class="stream-content" style="display: block;">
          <!--发送活动外包装 -->
        
        <table class="table table-striped" id="lists">
          <thead>
            <tr>
              <th>Name</th>
              <th>Member Num</th>
              <th><%= model_class.human_attribute_name(:created_at) %></th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @lists.each do |list| %>
              <%= render list %>
            <% end %>
          </tbody>
        </table>
        
        <hr />

        </div>

    </div> 

</div>
<!--   dashboard end   --> 
<!--   details pane   --> 
<div id="details-pane-outer">
	<div class="details-pane-shell">
		<div class="details-pane" id="details-pane" style="display: none; height: 585px; width: 415px; left: 530px; margin-top: 15px; -webkit-transition-property: none; ">
			<div class="inner-pane active">
				<div class="pane-toolbar pane-built-in">
					<a class="pane-close toolbar-control " rel="pane_close" href="javascript:void(0)">
						关闭 <span>×</span>
					</a>
					<br style="clear: both">
				</div>
				<div id="pane-load" style="overflow-y:scroll; ">
				</div>
			</div>
		</div>
	</div>
</div>
<!--   details pane  end --> 
<script type="text/javascript">
	$(function () {
   		$("a[rel=pane_close]").click(function(e) {
   			$("#details-pane").css("display","none");
     	})
	});
</script>
<script type="text/javascript">
	var strhost = window.location.host;
	var strprotocol = window.location.protocol;
	
	$(document).ready(function(){
		$("#details-pane").css("height",$(window).height() - 70);
		// 点击显示Pane_detail
		//$(".stream-item-content").click(function(e) {
		//    open_cam_pane($(this).attr("id").substring(2));
		//})
	});
	function showpane(){
		showLoading();
		$("#details-pane").css("display","block");
	    $(document).ready(function(){
	    	$("#details-pane").css("height",$(window).height() - 70);
		});
	}	

	function open_cam_pane(cam_id){
		showpane();
		var strurl = strprotocol + "//" + strhost + "/home/campaign";
	   	$.ajax({
			type: 'GET',
		    url: strurl,
		    data: {"cam_id":cam_id},
		    contentType: 'multipart/form-data',
		    datatype: 'json',
		    success:function(data)
		    {
		    	//alert(data);
		    	$("#pane-load").html(data);
		    	hideLoading();
		    },
		    error:function(xhr,r,e)
		    {
		    	alert(e);
		    	hideLoading();
		    }
		  });
	}

	//<!--   发送活动  search --> 
	function start_search(f){
		showLoading();
		//var txtq = $("#str_month").val();
		var strhost = window.location.host;
		var strprotocol = window.location.protocol;
		var strurl = strprotocol + "//" + strhost + "/home?f=" + f;
		//alert(strurl);
	    window.open(strurl,'_self');
	};
	//<!--   发送活动  search end -->
</script>


app/views/lists/new.js.erb
$("#form").html("<%= j render :partial => 'form' %>");
$("#form > form").replaceWith("<%= j render "form" %>");

app/views/lists/search.html.erb
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", :media => "all" %>
<%= stylesheet_link_tag "focusmore" %>
<style>
body{
 padding-top: 0px;
}
</style>
 <div class="main-content" style="width:100%;height:100%;">
  <!--
  <div class="page-header hidden">
    <table style="width:100%"><tr><td><h2><%= @list.name %> <small>成员共：<%= @list.members.size %></small></h2></td>
     <td style="float:right">
       <div style="float:right;margin-top:12px;">
                <%= link_to '添加名单', new_list_member_path(@list.id), :class => 'btn', :style => 'color: black' %>
                <%= link_to '批量导入', members_imexport_path(@list.id), :class => 'btn', :style => 'color: black' %>
              </div>
     </td></tr></table>
   </div>-->
   <div class="header">
    <%= @list.name %>
   </div>
   <div class="focus-center" style="background:transparent;height:35px;padding-top:5px;">
    <table><tr><td>
     <input id="search_input" type="text" placeholder="关键字搜索" name="name"  class="text_field span3" style="height:28px;">
    </td><td>
     <button type="submit" class="btn" onclick="members_search(<%= @list.id %>,$('#search_input').val());">名单搜索</button>
    </td></tr><table>
    </div>
    
    <div  style="padding:0px;">
     <div id="form"></div>
     <div id="sel_mes" class="stream-content" style="display: block;">
          <!--发送活动外包装 -->
    <table class="table table-striped">
     <thead class="focus-thead">
      <tr>
        <th></th>
        <th>名称</th>
        <th>邮件地址</th>
        <th>操作</th>
      </tr>
      </thead>
      <% @index = 1 if @members %>
      <%= render @members if @members %>

    </table>

    <%= will_paginate @members, :inner_window => 2, :outer_window =>1, :prev_label => '上一页 ', :next_label => '下一页 ' %>

        </div>

    </div> 

</div>

<script>
 function members_search(listid,keyword){
  alert(keyword);
  var strhost = window.location.host;
  var strprotocol = window.location.protocol;
  var strurl = strprotocol + "//" + strhost + "/lists/search"
  alert(strurl);
  showLoading();
  $.ajax({
   type: 'GET',
   url: strurl,
   data: {"listid":listid,"keyword":keyword},
   contentType: 'multipart/form-data',
   datatype: 'json',
   success:function(data)
   {
    alert(data)
    hideLoading();
   },
   error:function(xhr,r,e)
   {
    alert(e);
    hideLoading();
   }
   });
 }
</script>


app/views/lists/update.js.erb
$("#<%= dom_id @list %>").replaceWith("<%= j render @list %>");
<% @list = List.new %>
$("#form > form").replaceWith("<%= j render "form" %>");
$("#new_list")[0].reset();