config/routes.rb
require 'resque/server'
FocusMail::Application.routes.draw do
  get "campaigns/test_job"
  get "user/edit"
  post "user/update_password"

  devise_for :users

  root :to => 'home#index'
  match 'open/getstate' => 'open#getstate'
  match 'open/sendmail' => 'open#sendmail'
  match 'track.gif' => 'respond#track'
  match 'click' => 'respond#click'
  match 'testcode' => 'testcode#index'
  post 'testcode/save'
  post 'campaigns/mailtest'
  post 'useradmins/saveupdate'
  match 'send_email' => 'home#send_email', via: 'post'
  match 'generate_email' => 'home#generate_email', via: 'get'
  match 'preview/:campaign_id' => "home#preview", :as => :preview
  get 'report/export'

  resources :links
  resources :campaigns
  resources :campaign_members
  resources :categories do
    get 'update_member_count', :on => :member
    get 'member_search', :on => :member
  end
  resources :templates do
    resources :entries
    get "download", :on => :collection
  end
  resources :lists do
    resources :members
  end
  resources :useradmins

 
  match 'templates/saveimgurl', via: 'post'
  match 'campaigns/template_entries/:c_id/:t_id' => 'campaigns#template_entries'
  match 'campaigns/:id/deliver/', controller: 'campaigns', action: 'deliver', as: 'deliver_campaign'
  match 'campaigns/:id/copies/', controller: 'campaigns', action: 'copies', as: 'copies_campaign'
  #match 'campaigns/:id/mailtest/', controller: 'campaigns', action: 'mailtest', as: 'mailtest_campaign'

  match 'campaigns/:campaign_id/record' => 'campaigns#record', :as => :campaigns_record
  match 'members/export/:list_id' => 'members#export', :as => :members_export
  get 'members/import_template'
  
  match 'members/imexport/:list_id' => 'members#imexport', :as => :members_imexport
  match 'members/import' => 'members#import', :via => :post
  match 'templates/grade/:template_id' => 'templates#grade', :as => :templates_grade
  match 'templates/preview/:template_id' => 'templates#preview', :as => :templates_preview
  
  match ':controller(/:action(/:id(.:format)))'
  
  mount Resque::Server.new, :at => '/resque'
end

app/models/category.rb
class Category < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/categories_controller.rb
#encoding:utf-8
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @l_id = params[:lists_all]
    if @l_id != nil && @l_id != "" then
      lwhere = "id = #{@l_id} and is_used != false"
    else
      lwhere = ""
    end
    user_id = current_user.id
    @category = List.new
    @category.org_id = FocusMail::ListUserorg::userorg_id(user_id)
    #userids = [6,7,8,9,10,12,13]
    puts "#"*40+user_action_org.to_s
    if user_action_org then
      @lists = List.paginate(:page => params[:page], :per_page => 5, :conditions => lwhere =="" ? "is_used != false" : lwhere, :order => "updated_at desc")
      @lists_all = List.where([lwhere =="" ? "is_used != false" : lwhere]).order("created_at desc")
      @list = List.new
      @category = List.new
      @category.org_id = FocusMail::ListUserorg::userorg_id(user_id)
    else
      controller = "List"
      orglist = FocusMail::ListUserorg::userorg_list(user_id, controller).join(",")
       puts "#"*40+orglist.to_json
      if orglist.length == 0 then
        @lists = List.paginate(:page => params[:page], :per_page => 5, :conditions => "1=2 and is_used != false", :order => "updated_at desc")
        @lists_all = List.where(["1=2 and is_used != false"])
      else
        @lists = List.paginate(:page => params[:page], :per_page => 5, :conditions => lwhere == "" ? "id in (#{orglist}) and is_used != false" : "is_used != false", :order => "created_at desc")
        @lists_all = List.where(["id in (#{orglist}) and is_used != false"])
      end
      @category = List.new
      @category.org_id = FocusMail::ListUserorg::userorg_id(user_id)
    end
    @memberorg = MemberOrg.paginate(:page => params[:page], :per_page => 20)
    user_action_log(0,params[:controller],"index")
    WillPaginate::ViewHelpers.pagination_options[:previous_label] = '上一页'
    WillPaginate::ViewHelpers.pagination_options[:next_label] = '下一页' 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memberorg }
    end
  end
  
  def new
    #@list = List.new
    user_id = current_user.id
    @category = List.new
    @category.org_id = FocusMail::ListUserorg::userorg_id(user_id)
    user_action_log(0,params[:controller],"new")

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end
  
  def edit
    @category = List.find(params[:id])
    user_action_log(params[:id],params[:controller],"edit")

    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def create
    puts "#"*50
    List.create({
      :name => params[:name],
      :org_id => params[:org_id],
      :is_used => true
    })
    respond_to do |format|
      format.js
    end
  end
  
  def update
    @lupdate = List.update(params[:id],{
      :name => params[:name]
    })
    session[:list_id] = @lupdate.id
  end
  
  def destroy
    @list = List.find(params[:id])
    @list.update_attribute(:is_used,false)
    puts "*"*100
    puts "categories_controlle"
    #@list.destroy
    user_action_log(params[:id],params[:controller],"delete")
  end
  
  def update_member_count
    @list_id = params[:id]
    list = List.find(@list_id)
    @member_count = ListsMembers.where("list_id=?",@list_id).count
    if list.member_count.present? then
      if @member_count > list.member_count.to_i then
        list.update_attribute(:member_count, @member_count.to_s)
      end
    else
      list.update_attribute(:member_count, @member_count.to_s)
    end
  end
  
  def member_search
    list_id = params[:id]
    @keyword = params[:keyword]
    @list = List.find(list_id)
    params[:per_page] = 15
    @members = @list.members.where("email like '%#{@keyword}%'")
                    .paginate(:page => params[:page], :per_page => params[:per_page],:order => "updated_at desc")
    respond_to do |format|
      format.html { render :layout => false, :template => "/categories/member_search" }
    end
  end
  
  def list_split
    list_id   = params[:list_id].to_i
    split_num = params[:split_num].to_i
    
    list = List.find(list_id)
    lists_members = ListsMembers.where("list_id =#{list_id}")
    
    user_id = current_user.id
    org_id = FocusMail::ListUserorg::userorg_id(user_id)
    
    #存放批量list
    lists = Array.new()
    (1..split_num).each do |sn|
      ll =List.new({
        :name => "#{list.name}_#{sn}",
        :org_id => org_id,
        :is_used => true
      })
      if ll.save then 
        lists.push(ll)
        puts "-"*50
        puts ll.name
      else
        puts "*"*50
        puts "no"
      end
    end
    
    lists_members.each_with_index do |lm,ii|
      index = ii%split_num
      puts "*"*50
      puts index
      current_list = lists[index]
      
      if current_list then
        puts current_list.name
          listsmembers = ListsMembers.where(["list_id = :l and member_id = :m", { :l => current_list.id , :m => lm.member_id }])
          if listsmembers.count == 0 then
            ListsMembers.create({
              :list_id => current_list.id,
              :member_id => lm.member_id
            })
          end
      else
        puts lists.length
      end
    end
    
    render :text => "over"
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def memberorg(listid)
    mo = []
    lma = Array.new
    lms = ListsMembers.where(["list_id = :lid", :lid => listid]).all
    if lms.count > 0 then
      lms.each do |lm|
        lma.push(lm.id)
      end
    end
    moo = 0
    if lma.count > 0 then
      lma = lma.join(",")
      moos = MemberOrgObject.find(:all, :select => "max(member_org_id) as org_id", :conditions => "list_member_id in(#{lma})", :group => "member_org_id")
      mooa = Array.new
      if moos.count > 0 then
        moos.each do |moot|
          mooa.push(moot.org_id)
        end
        mooa = mooa.join(",")
      end
      if mooa.length > 0 then
        mo = MemberOrg.where(["id in (#{mooa})"]).all
      end
    end
    
    name_num = Array.new
    mo.each do |m|
      name_num.push(Org_Name_Num.new(m.name,m.member_org_object.where("list_member_id in (#{lma})").count))
    end
    name_num = name_num.sort!{|a,b| b.org_number <=> a.org_number }
    return mo,lma,name_num
  end
  
  class Org_Name_Num
    def initialize(name, number)
      @org_name = name
      @org_number = number
    end
    attr_accessor :org_name, :org_number
  end
end

app/views/categories/Outer_Upload.html.erb
<iframe id="Outer_Upload" marginwidth="0px" height="200px" width="350px" frameborder="0" scrolling="auto" allowTransparency="true" src="http://210.14.76.206:4567/member/index?list_id=<%=h @list_id %>&user_id=<%=h current_user.id %>">
 
</iframe>

app/views/categories/_form.html.erb
<%= hidden_field_tag 'org_id', @category.org_id %>
<span>
  <%= label_tag 'name', '列表名称', :class=>"hidden" %>
  <%= text_field_tag 'name', @category.name, :class => 'text_field span3',:placeholder => "名单列表名称",:id=>"category_form_name" %>

  <a class="btn" type="button" id="category_submit">新建列表</a>
</span>



app/views/categories/create.js.erb
$('#category_form_name').attr("value","");
window.location.reload();
hideLoading();


app/views/categories/destroy.js.erb
window.location.reload();

////删除之前，取得兄弟节点第一个
//var next_br = $("#<%= dom_id @list %>").siblings().eq(0).attr("id");
//
////移除当前删除列表
//$("#<%= dom_id @list %>").remove();
//
////右侧显示当前删除列表下面的第一个列表
//var next_id = next_br.split("_")[1];
//var jud_str = next_br.split("_")[0];
//
//var str = "";
////判断该兄弟id是否是dom_id生成的字符串，有误判的可能。
//if(jud_str=="list"){
// src = "/lists/"+next_id+"/members";
//}
////加载对应名单列表的名单
//$('#list_member').attr("src",src);
//
////删除名单列表选择下拉框中信息
//var select = document.getElementById("lists_all");
//var option = select.options;
//var node = select.childNodes;
//for(var i=option.length-1;i>=0;i--){
// if(option[i].value==next_id){
//  select.removeChild(option[i]);
//  select.removeChild(node[i]);
//  alert(i);
//  alert(option[i].value);
// }
//}


app/views/categories/edit.js.erb
$("#form").html("<%= j render :partial => 'form' %>");
$("#form > form").replaceWith("<%= j render "form" %>");

app/views/categories/index.html.erb
<style>
.stream-item:hover{
 cursor: default;
}
</style>
   
   <div class="main-content" style="width:540px;">
     <div class="header">
                   邮件列表
       <span style="float:right;margin-top:-3px;">
       <%= form_tag '/categories/index', :class => 'form-horizontal', :id => "uploadsubmit" do %>
         <%= select_tag "lists_all", options_from_collection_for_select(@lists_all, "id", "name", @l_id),{:include_blank => true, :style => "width: 220px", :class => "chzn-select-deselect", :"data-placeholder" => "查找邮件列表"} %>
       <% end %>
       </span>
     </div><!--header-->

      <!--Body content-->
    <div class="js-stream-items stream-items" style="height: 900px;border-radius: 0px 0px 5px 5px;background:white;padding-bottom:10px;">
     <% if @lists.count > 0 %>
      <% @lists.each do |list| %>
      <!--<% mos,lma,name_num = memberorg(list.id) %>-->
      <div class="js-stream-item stream-item" media="true" data-item-type="tweet"  id="<%= dom_id list %>">
       <div class="stream-item-content tweet" data-is-reply-to="false">
       <table class="focus-content" style="width:100%;">
         <tr class="tweet-row" style="height:22px;">
          <td>
           <a class="focus-rel" style="color:blue;" id="orglist<%= list.id %>" onclick="edit_list(<%= list.id %>,false,true)" 
            data-placement="top" rel="tooltip" data-original-title="点击标题进行修改">
            <%= list.name.present? ? (list.name.length > 25 ? "#{list.name[0..20]}..." : list.name) : "unset" %>
           </a>

           <span id="editlist<%= list.id %>" class="hidden">
            <%= form_tag "/categories/update/#{list.id}", :style=>"margin:0px;" , remote: true, :id => 'categories_form' do %>
            <%= hidden_field_tag :id => 'org_id' %>
            <span>
              <%= text_field_tag 'name', list.name, :class => 'text_field' %>
            </span>
            <span>
              <%= submit_tag '保存', :class => 'btn btn-mini'%>
              <input type="button" href="#" class="btn btn-mini" onclick="edit_list(<%= list.id %>,true,false)" value="取消">
            </span>
            <% end %>
          </span>
          </td>
         </tr>

         <tr class="tweet-row">
            <td>
              <ul>
                <li>邮箱数量：
                 <span id="list_<%= list.id %>_mc" style="display:inline-block;width:55px;"><%= list.member_count.present? ? list.member_count : 0 %></span>
                  <a href="/categories/<%= list.id %>/update_member_count" id="list_<%= list.id %>_mc_refresh" style="display:none;" class='focus-icon refresh-icon' rel='tooltip' data-remote='true' data-placement='top' data-original-title='点击刷新数据'>
                  </a>
                </li>
                 <li>创建时间：<%= list.created_at.strftime("%Y/%m/%d") %></li>
                 <li>修改时间：<%= list.updated_at.strftime("%Y/%m/%d") %></li>
                 <li>上传状态：
                   <iframe id="iframe_<%= dom_id list %>"　marginwidth="0px" height="15px" width="60px" frameborder="0" scrolling="no" style="padding:0px;margin:0px 0px 0px -5px;"
                    allowTransparency="true" src="http://192.168.0.114/member/state?list_id=<%=h list.id %>&user_id=<%=h current_user.id %>">
                   </iframe>

                  <a href="javascript:void(0);" style="display:none;" id="list_<%= list.id %>_job_refresh" onclick="$('#iframe_<%= dom_id list%>').attr('src',$('#iframe_<%= dom_id list%>').attr('src'));" class='focus-icon refresh-icon' rel='tooltip' data-remote='true' data-placement='top' data-original-title='点击刷新状态'>
                  </a>
                 </li>
              </ul>
            </td>
         </tr>
         <tr class="tweet-row hidden">
          <td align="left">
            <%= link_to '+1', new_list_member_path(list.id), :class => 'btn btn-mini', :style => 'width:23px;',:remote=>true,
              :rel=>"tooltip", :title=>"添加一个名单" %>
            <%= link_to '+n', members_imexport_path(list.id), :class => 'btn btn-mini', :style => 'width:23px;',:remote=>true,
            :rel=>"tooltip", :title=>"批量导入名单" %>
            <a class='btn btn-mini', style = 'width:23px;',:rel="tooltip", :title="split list" 
            onclick="list_split(<%=list.id%>)">split</a>
            <%= link_to '删除', category_path(list), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini', :remote => true %>
            <a href="javascript:void(0)" style="margin-left:15px;margin-top:5px;" onclick="list_refresh(<%= list.id %>)" class='focus-icon refresh-icon' style="margin:5px 0px 0px 10px;" rel='tooltip' data-remote='true' data-placement='top' data-original-title='刷新数据、显示名单列表'>
           </a>
          </td>
         </tr>
        </table>
      </div><!--stream-item-->
    </div><!--item-content-->
    
     <% end %><!-- each -->
    
     <!--Body content-->
     <div class="focus-center">
     <%= will_paginate @lists ,:inner_window => 1, :outer_window => 1 , :previous_label => '上一页 ' , :next_label => '下一页 ' %>
    </div>
     <% end %><!-- if -->
    </div><!--stram-item-->
     </div>
   <!--main-content-->
    

    <div class="dashboard" style="float:right;padding:0px;">
     
     <div class="databoard">
     <div class="header">新建列表</div>
     <div class="body">
         <!-- 新建名单-->
         <%= form_tag '/categories/create', :class => 'form-horizontal' , remote: true, :id => 'categories_form' do %>
           <%= render "form" %>
         <% end %>
      </div>
    </div>
      
     <div class="databoard" style="height:820px;">
     <div id="main_content">
      <% if @lists.count > 0 %><!--<%= session[:list_id] == nil ? @lists[0].id : session[:list_id] %>-->
      <iframe id="list_member" src="/lists/<%= session[:list_id] == nil ? @lists[0].id : session[:list_id] %>/members" width="100%"  frameborder="no" border="0" marginwidth="0" marginheight="0" scrolling="no" allowtransparency="yes" style="-webkit-border-radius:4px;-moz-border-radius:4px;border-radius:4px;">    
      </iframe>
      <% end %>
     </div>
     <div id="members_imexport">
     </div>
     </div>
   </div><!-- databoard-->
   <!--add-modal-->
   <div id="add_member" class="modal fade">
    <div class="modal-header header">
      <button type="button" class="focus-close" data-dismiss="modal">&times;</button>
              添加新名单
    </div>
    <div class="modal-body">
    </div>
   </div>
  <!--add modal-->
  <a href="#add_member" id="add_btn" role="button" class="hidden" data-toggle="modal"></a>

   <div id="list_split_model" class="modal fade">
    <div class="modal-header header">
      <button type="button" class="focus-close" data-dismiss="modal">&times;</button>
        List Split
    </div>
    <div class="modal-body">
     split num:<%= text_field_tag 'split_num', nil, :class => 'span2', :placeholder => 'split num'  %>
    </div>
    <div class="focus-center">
     <button class="btn btn-primary" onclick="list_split_submit()">Submit</button>
    </div>
   </div>
  <!--add modal-->
  <a href="#list_split_model" id="list_split" role="button" class="hidden" data-toggle="modal"></a>
  <%= hidden_field_tag 'splited_list_id',    nil %>

<script type="text/javascript">
 //新建列表 提交按钮
 $("#category_submit").click(function(){
   var list_name = $.trim($("#category_form_name").val());
   if(list_name.length==0){
    alert("列表创建失败\n原因：\n新建列表名称不可以为空");
   }else{
    $(this).submit();
    showLoading("保存中");
   }
 });
 $(".chzn-select-deselect").chosen({allow_single_deselect:true});
 $("#list_member").load(function(){
  var mainheight = $(this).contents().find("body").height();
  var span = $(".dashboard").height();
  if(span > mainheight)
  {
   $(this).height(span);
  }
  else
  {
   $(this).height(mainheight);
  }
  $(this).height(820);
 }); 
 //选择列表下拉列表时，自动提交
 $("#lists_all").change(function() {
   $("#uploadsubmit").submit();
 });
 //点击列表区域显示该列表邮件名单
 function list_refresh(listid)
 {
  //刷新列表名单数量/上传状态
  member_count = "#list_"+listid+"_mc_refresh";
  upload_job = "#list_"+listid+"_job_refresh";
  $(member_count).trigger("click");
  $(upload_job).trigger("click");
  //
  $('#list_member').attr("src","/lists/" + listid + "/members");
  //在批量导入的js操作中，会隐藏邮件列表;
  $("#members_imexport").addClass('hidden');
  $("#main_content").removeClass('hidden');
 }
 //点击列表标题进行编辑时，编辑框与显示框的显示隐藏切换！
 function edit_list(id,ob,eb){
  var strid = String(id);
  if(ob==true) $('#orglist'+strid).css('display','block'); else $('#orglist'+strid).css('display','none');
  if(eb==true) $('#editlist'+strid).removeClass('hidden'); else $('#editlist'+strid).addClass('hidden');
 }
 
 function list_split(list_id){
  $("#list_split").trigger("click");
  $("#splited_list_id").val(list_id);
 }
 function list_split_submit(){
   var list_id = $("#splited_list_id").val();
   var split_num = $("#split_num").val();
   
   alert(list_id);
   alert(split_num);
   var strhost = window.location.host;
   var strprotocol = window.location.protocol;
   var strport = window.location.port;
   if(strport > 0){
     if(strhost.indexOf(strport)==-1){
      strhost = strhost + ":"+String(strport)
     }
   }
   var strurl = strprotocol+"//"+strhost+"/categories/list_split";
 
   
    $.ajax({
    type: 'POST',
    url: strurl,
    contentType: 'multipart/form-data',
     headers: {
           'X-Transaction': 'POST Example',
           'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
         },
    datatype: 'json',
    data:{"list_id": list_id, "split_num": split_num },
    success:function(data)
    {
     alert(data);
      window.location.reload();
    },
    error:function(xhr,r,e)
    {
       alert("Create Tag Fail!");
    }
   });
  
 }

</script>



app/views/categories/member_search.html.erb
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", :media => "all" %>
<%= stylesheet_link_tag "focusmore" %>
<style>
body{
 padding: 0px;
 -webkit-border-radius:4px;-moz-border-radius:4px;border-radius:4px;
 margin:0px;
}
</style>

 <div style="border: solid 2px lightgray;-moz-border-radius:10px; border-radius:10px;margin:3px 0 3px 10px;padding-top:10px;width:350px;height:25px;">
     <span style="float:left;margin-left:5px;">搜索关键字:[<span style="color:green;"><%= @keyword.length>15 ? "#{@keyword[0..15]}..." : @keyword %></span>] 结果: [<span style="color:green;"><%= @members.count %></span>]条</span>
 </div>
 <!--搜索 结果列表-->
 <table class="table table-striped" style="margin-left:0px;">
  <thead class="focus-thead">
   <tr>
     <th style="width:15%;">序号</th>
     <th style="width:30%;">名称</th>
     <th style="width:40%;">邮件地址</th>
     <th style="width:15%;">操作</th>
   </tr>
   </thead>
   <% @index = params[:page].to_i >= 1 ? ((params[:page].to_i - 1) * params[:per_page ].to_i + 1 ) : 1 %>
   <%= render @members if @members %>
 </table>

 <div class="focus-center">
   <%= will_paginate @members,:inner_window => 0,:outer_window => 0,:previous_label => '上一页 ', :next_label => '下一页 ' %>
 </div>
</div>

app/views/categories/new.js.erb
$("#templates_form").html("<%= j render :partial => 'form' %>");


$("#templates_form > form").addClass("box");
$("#fjzip").click(function(){
 if($(this).text() == "zip上传")
 {
  $("#htmlsource").addClass("hidden");
  $("#zipfile").removeClass("hidden");
  $(this).text("内容填写");
 }
 else
 {
  $("#htmlsource").removeClass("hidden");
  $("#zipfile").addClass("hidden");
  $(this).text("zip上传");
 }
});



app/views/categories/update.js.erb
//window.location.reload();
//$('#list_member').attr("src","/lists/<%= session[:list_id] %>/members");

$("#orglist<%= params[:id] %>").html("<%= @lupdate.name %>");
$('#orglist<%= params[:id] %>').css('display','block'); 
$("#editlist<%= params[:id] %>").addClass('hidden');

app/views/categories/update_member_count.js.erb
showLoading('[邮箱数量]更新完毕');
$('#list_<%= @list_id %>_mc').html("<%= @member_count%>");
hideLoading();